options:
  install_sources:
    default: ''
    type: string
    description: >
      By default, layer-puppet installs Puppet packages from the Ubuntu archive.
      Set this option to override the installation repository. See the
      layer-apt README for more details.
  install_keys:
    default: ''
    type: string
    description: >
      Signing keys (if needed) for repostories configured by the
      'install_sources' option above. See the layer-apt README for more details.
